name: Build and publish python package

on:
  pull_request:
    types:
      - closed

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install bumpver>=2022.1119 build twine
      - name: Check MAJOR changes
        if: "startsWith(github.event.pull_request.title, 'feat!:')"
        run: echo "VERSION_COMPONENT=major" >> $GITHUB_ENV
      - name: Check MINOR changes
        if: "startsWith(github.event.pull_request.title, 'feat:')"
        run: echo "VERSION_COMPONENT=minor" >> $GITHUB_ENV
      - name: Check PATCH changes
        if: "startsWith(github.event.pull_request.title, 'fix:')"
        run: echo "VERSION_COMPONENT=patch" >> $GITHUB_ENV
      - name: Print VERSION_COMPONENT env
        run: echo ${{ env.VERSION_COMPONENT }}
      - name: Bump version
        run: |
          git config --global user.email "elder_rn@hotmail.com"
          git config --global user.name "Elder Santos"
          bumpver update --${{ env.VERSION_COMPONENT }}
      - name: Build and upload package
        run: |
          python -m build
          twine check dist/*
          twine upload -r testpypi dist/* -u ${{ secrets.TWINE_USERNAME }} -p ${{ secrets.TWINE_PASSWORD }}
